from typing import Callable, Any

class EvolutionaryAlgorithm:
    def __init__(
        self,
        initializer: Any,
        operators: Any,
        fitness: Callable[[list], float],
        termination: Any,
        population_size: int,
        comparator: Maximize | Minimize | Callable[[float, float], bool] | None = ...,
        seed: Optional[int] = ...,
    ) -> None: ...
    def run(self) -> RunResult: ...
    def run_with(self, collector: Any) -> Any: ...

class RunResult:
    @property
    def population(self) -> list[Individual]: ...
    @property
    def generations(self) -> int: ...
    @property
    def total_duration(self) -> float: ...
    @property
    def best_fitness(self) -> list[float]: ...
    @property
    def generation_durations(self) -> list[float]: ...
    def best(self) -> Individual: ...

class Individual:
    @property
    def genome(self) -> list[int] | list[float]: ...
    @property
    def fitness(self) -> float: ...

class Maximize:
    def __init__(self) -> None: ...

class Minimize:
    def __init__(self) -> None: ...

class MaxGenerations:
    def __init__(self, generations: int) -> None: ...

class Grammar:
    @staticmethod
    def builder() -> GrammarBuilder: ...

class GrammarBuilder:
    def rule(self, name: str, productions: list[list[str]]) -> GrammarBuilder: ...
    def start(self, name: str) -> GrammarBuilder: ...
    def build(self) -> Grammar: ...

class StandardMapper:
    def __init__(self, max_wraps: int) -> None: ...

class GeFitness:
    def __init__(
        self,
        grammar: Grammar,
        mapper: Any,
        evaluator: Callable[[str], float],
        penalty: float = ...,
    ) -> None: ...
    def __call__(self, genome: list[int]) -> float: ...

class Experiment:
    def __init__(self, factory: Callable[[], EvolutionaryAlgorithm], trials: int) -> None: ...
    def run(self) -> list[Any]: ...
