from typing import Any

class Tournament:
    def __init__(self, tournament_size: int) -> None: ...

class Elitism:
    def __init__(self, amount: int = ...) -> None: ...

class RouletteWheel:
    def __init__(self) -> None: ...

class Rank:
    def __init__(self) -> None: ...

class Sus:
    def __init__(self, count: int) -> None: ...

class SinglePoint:
    def __init__(self) -> None: ...

class TwoPoint:
    def __init__(self) -> None: ...

class Uniform:
    def __init__(self) -> None: ...

class Arithmetic:
    def __init__(self) -> None: ...

class RandomReset:
    def __init__(self) -> None: ...

class Swap:
    def __init__(self) -> None: ...

class Inversion:
    def __init__(self) -> None: ...

class Scramble:
    def __init__(self) -> None: ...

class Creep:
    def __init__(self, step: int) -> None: ...

class Gaussian:
    def __init__(self, std_dev: float) -> None: ...

class SegmentDuplication:
    def __init__(self, max_segment_fraction: float, max_genome_len: int) -> None: ...

class SegmentDeletion:
    def __init__(self, max_segment_fraction: float, min_genome_len: int) -> None: ...

class Fill:
    def __init__(self, operator: Any) -> None: ...

class FillFixed:
    def __init__(self, operator: Any, size: int) -> None: ...

class Pipeline:
    def __init__(self, operators: list[Any]) -> None: ...

class Combine:
    def __init__(self, operators: list[Any]) -> None: ...

class Weighted:
    def __init__(self, pairs: list[tuple[Any, int]]) -> None: ...

class Proportional:
    def __init__(self, pairs: list[tuple[Any, int]]) -> None: ...

class Repeat:
    def __init__(self, operator: Any, n: int) -> None: ...

class Identity:
    def __init__(self) -> None: ...

class WithRate:
    def __init__(self, operator: Any, rate: float) -> None: ...
