from typing import Any

class ParallelFill:
    def __init__(self, operator: Any, target_size: int) -> None: ...

class ParallelRandomReset:
    def __init__(self) -> None: ...

class ParallelSwap:
    def __init__(self) -> None: ...

class ParallelInversion:
    def __init__(self) -> None: ...

class ParallelScramble:
    def __init__(self) -> None: ...

class ParallelCreep:
    def __init__(self, step: int) -> None: ...

class ParallelGaussian:
    def __init__(self, std_dev: float) -> None: ...
